### ISSUE TITLE
Different flag for bots

### ISSUE THREAD

**Issue by congratulatio** [airmash-refugees/game-ideas#19]
For recognised bots, it would be useful to display a different flag to more easily distinguish them from human players on the battlefield.

The Jolly Roger is a popular bot flag already, so perhaps something similar to that. The [Wikipedia article](https://en.wikipedia.org/wiki/Jolly_Roger) on that flag notes that:

> If a ship then decided to resist, the Jolly Roger was taken down and a red flag was flown, indicating that the pirates intended to take the ship by force and without mercy. In the mid-18th century, Sir Richard Hawkins confirmed that pirates gave quarter beneath the black flag, while no quarter was given beneath the red flag.

As the bots do indeed attack our ships forcefully and without mercy, how about this:

![image url](https://user-images.githubusercontent.com/45519482/65807461-7e291680-e186-11e9-91bb-7bdd36545cb6.png)

**Comment by peace2000** [comment]
Some way to distinguish bots immediately would be great. My suggestion, taken from another issue:

"Could bots have some kind of suffix at their name that cannot be used / mimicked by human players? For e.g. grey colored [bot] tag or something?"
