### ISSUE TITLE
A new game mode to replace "btr" call DM=Deathmatch

### ISSUE THREAD

**Issue by Johnnyouknow** [airmash-refugees/game-ideas#24]
Deathmatch, or DM, is a type of gameplay mode  
The objective of a deathmatch is to frag as many players in the game as possible while keeping yourself from being fragged. When the game ends either by gamers reaching the end of the level or a preset time or frag count limit, the gamer who accumulated the most frags(kills) in the DM game is the winner of the deathmatch.

DM can also be set to a "teamplay deathmatch" mode where teams (called clans) work together to obtain a higher combined frag count than the opposing teams in the game.

**Comment by ghost** [comment]
Hey MJ, I thought this was a great idea. I think you should leave it open
