### ISSUE TITLE
Unify starma.sh and airmash.online games data

### ISSUE THREAD

**Issue by congratulatio** [airmash-refugees/game-ideas#31]
@steamroller-airmash I was thinking for easier game data maintenance, we should have both frontends operate on the same data source.

I submitted a PR to bombita's StarMash repository for one potential option: https://github.com/Molesmalo/StarWarsMod4AirMash/pull/15, this pulls the game data straight from https://airmash.online/games.

Another option may be for starma.sh backend to generate its games endpoint from this: https://github.com/airmash-refugees/airmash-backend/blob/master/games.txt, which is the file used to generate https://airmash.online/games.

**Comment by steamroller-airmash** [comment]
I think having the starma.sh backend poll that data file would be best. 
I'll try to set that up sometime this week :)

**Comment by congratulatio** [comment]
I moved the game server data to a new repo [airmash-games](https://github.com/airmash-refugees/airmash-games).

This is for https://github.com/airmash-refugees/airmash-frontend/issues/17, so it can be shared more cleanly with both [airmash-frontend](https://github.com/airmash-refugees/airmash-frontend) and [airmash-backend](https://github.com/airmash-refugees/airmash-backend) repos.

**Comment by steamroller-airmash** [comment]
[starma.sh](http:://starma.sh) is now using the data from the games repo. :tada: 

It updates every hour so it'll take a little while for new servers to be added whenever the file gets updated but it'll be way faster than me doing it by hand.
