### ISSUE TITLE
What's wrong with airmash?

### ISSUE THREAD

**Issue by Johnnyouknow** [airmash-refugees/game-ideas#41]
- Is airmash down again?
- I tried to login but i can't
- It  doesn't show the regions

**Comment by congratulatio** [comment]
Was this on airmash.online and if so do you have a date and time for when this occurred? So I can check the logs for any disturbance. Thanks!

**Comment by wight-airmash** [comment]
@congratulatio https://airmash.online/games returned empty 200 response during 10-15 minutes after this issue was created.

**Comment by congratulatio** [comment]
Thanks, I think I see what happened. It was a concurrency issue, I need make sure the backend task that retrieves the player count from each server doesn't overlap with its next invocation. Fixing it now, sorry for the downtime earlier.

**Comment by congratulatio** [comment]
Fixed in https://github.com/airmash-refugees/airmash-backend/commit/4b9c26f78ea9b68c3f7ccded6e1fca4924af2915

**Comment by congratulatio** [comment]
If the `/games` endpoint becomes unexpectedly unavailable in future, https://github.com/airmash-refugees/airmash-frontend/commit/488324308a067c0a9b5be91c864575dc4cdaa3e9 should permit players to still connect to the game servers.
