### ISSUE TITLE
Increase rate of dropping a upgrade box after kill if a player has some unused upgrades 

### ISSUE THREAD

**Issue by tdiff** [airmash-refugees/game-ideas#54]
Not sure how it works at present, but I believe that probability of dropping an upgrade from a killed player should be higher if he has some unused upgrades.

**Comment by wight-airmash** [comment]
[Already](https://github.com/wight-airmash/ab-server/blob/466f3c1666232eb763adea5895bcdf0b484acce8/src/server/modes/base/maintenance/players/kill.ts#L127).
